### ISSUE TITLE
Lookup function in Q expression

### ISSUE THREAD

**Issue by highpost** [coady/django-model-values#7]
I'm new to django-model-values and I really think it will be worth the time to learn it well. I especially like the pandas-like notation. Right now I'm trying to understand understand Lookup functions.

Consider the following Q expression:

Q(sales__gt = 100.00)

Now I would like to use __round__ to round the sales value (which is a float) to the nearest penny. Is that even possible? I've looked at the examples in test_all.py, but I'm still in a fog.

Thanks.

**Comment by coady** [comment]
Yes, [Round](https://docs.djangoproject.com/en/3.0/ref/models/database-functions/#round) can be used as a function, or as a lookup.  But to use it as a lookup, it has to registered as a transform with `FloatField` as described in that link.

```python
In [1]: from model_values import F                                                                                                                                                                                                              

In [2]: round(F.sales)                                                                                                                                                                                                                          
Out[2]: Round(F(sales))

In [3]: F.sales.round > 100.0                                                                                                                                                                                                                   
Out[3]: <Q: (AND: ('sales__round__gt', 100.0))>
```

**Comment by auvipy** [comment]
> Yes, [Round](https://docs.djangoproject.com/en/3.0/ref/models/database-functions/#round) can be used as a function, or as a lookup. But to use it as a lookup, it has to registered as a transform with `FloatField` as described in that link.
> 
> ```python
> In [1]: from model_values import F                                                                                                                                                                                                              
> 
> In [2]: round(F.sales)                                                                                                                                                                                                                          
> Out[2]: Round(F(sales))
> 
> In [3]: F.sales.round > 100.0                                                                                                                                                                                                                   
> Out[3]: <Q: (AND: ('sales__round__gt', 100.0))>
> ```

can we add this to documentation?

**Comment by coady** [comment]
Added in 3115244.

**Comment by auvipy** [comment]
thanks!
